name: Update Badge

on:
  schedule:
    - cron: '0 1 * * *'  # Runs every 12 hours
  workflow_dispatch:  # Allows manual trigger

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2
      
    - name: Update README.md with AWK
      run: |
        RANDOM_STRING=$(openssl rand -hex 8)
        awk -v random="$RANDOM_STRING" '{ gsub(/tryhackme-badge-workflow\/main\/badge\.png\?version=[0-9a-fA-F]+/, "tryhackme-badge-workflow/main/badge.png?version=" random); print }' README.md > temp_README.md && mv temp_README.md README.md
        cat README.md

    - name: Commit and push if changes are detected
      run: |
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'
        git add README.md
        git diff-index --quiet HEAD || git commit -m "Automatically update badge query string with AWK"
        git push
