name: Update Badge

on:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2
      
    - name: Update README.md with AWK
      run: |
        # Generate a unique query string using the current UNIX timestamp
        UNIQUE_STRING=$(date +%s)
        # Use awk to update the README.md file with the new badge URL
        awk -v unique="$UNIQUE_STRING" '{ if ($0 ~ /!\[TryHackMe Badge\]/) { print "![TryHackMe Badge](https://raw.githubusercontent.com/Robinzor/tryhackme-badge-workflow/main/badge.png?version=" unique ")" } else { print } }' README.md > temp_README.md && mv temp_README.md README.md
        # Display the modified README contents to verify the operation
        cat README.md
        
    - name: Commit and push if changes are detected
      run: |
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'
        git add README.md
        if ! git diff --cached --quiet; then
          git commit -m "Auto Refresh"
          git push
        fi
