name: TryHackMe Update Badge

on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:
jobs:
  tryhackme-badge-update:
    name: Update TryHackMe badge
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with:
          # Replace with your tryhackme username
          username: "robinzor"
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
