name: TryHackMe Update Badge

on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:

jobs:
  tryhackme-badge-update:
    name: Update TryHackMe badge
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: .github/workflows/action.yml@main
        with:
          username: "robinzor"
