name: Update README Image

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *' # Every 6 hours

jobs:
  update-readme-image:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Fetch page content and extract base64 image
      run: |
        URL="https://tryhackme.com/badge/1604750"
        # Fetch the content and extract the base64 encoded part
        ENCODED_IMAGE=$(curl -s $URL | grep -oP 'document\.write\(window\.atob\("\K[^"]+' | head -n 1)
        # Decode it to get the HTML content
        DECODED_HTML=$(echo $ENCODED_IMAGE | base64 --decode)
        # Extract the image URL
        IMAGE_URL=$(echo $DECODED_HTML | grep -oP 'src="\K[^"]+')
        echo "Extracted Image URL: $IMAGE_URL"
        
        # Update README.md (Ensure you tailor the sed command to match your README's existing format)
        sed -i "s|https://tryhackme-badges.s3.amazonaws.com/Robinzor.png|${IMAGE_URL}|" README.md

    - name: Commit and push if changes are detected
      run: |
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'
        git add README.md
        git diff-index --quiet HEAD || git commit -m "Automatically update TryHackMe badge image URL"
        git push
