name: Update README Image

on:
  workflow_dispatch: # Enables manual trigger from GitHub UI
  schedule:
    - cron: '0 */6 * * *' # Every 6 hours

jobs:
  update-readme-image:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3 # Updated to the latest version

    - name: Set up Node.js 20
      uses: actions/setup-node@v3 # Updated to use Node.js 20
      with:
        node-version: '20' # Specify Node.js 20

    - name: Fetch page content and decode base64 image
      run: |
        URL="https://tryhackme.com/badge/1604750"
        # Fetch the content and extract the base64 encoded part
        ENCODED_PART=$(curl -s $URL | grep -oP 'document\.write\(window\.atob\("\K[^"]+')
        
        # Decode and process to extract the image URL
        DECODED_HTML=$(echo $ENCODED_PART | base64 --decode)
        
        # Assuming the DECODED_HTML contains an img src, extract it
        # This step might require adjustment based on the actual HTML structure
        IMAGE_URL=$(echo $DECODED_HTML | awk -F 'src="' '{print $2}' | awk -F '"' '{print $1}')
        
        echo "Extracted Image URL: $IMAGE_URL"
        
        # If IMAGE_URL is empty or not valid, you might not want to proceed with replacements
        if [[ ! -z "$IMAGE_URL" && "$IMAGE_URL" =~ ^https ]]; then
          # Update README.md with the new image URL
          sed -i "s|https://tryhackme-badges.s3.amazonaws.com/Robinzor.png.*|![TryHackMe]($IMAGE_URL)|" README.md
          
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add README.md
          git commit -m "Update README with new TryHackMe badge image" || echo "No changes to commit"
          git push
        else
          echo "Valid image URL not extracted, skipping update."
