name: TryHackMe Update Badge

on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:

jobs:
  tryhackme-badge-update:
    name: Update TryHackMe badge
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install node-fetch

      - name: Run script to update badge
        run: node index.js
