name: TryHackMe Update Badge

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  tryhackme:
    name: Update this Repo with TryHackMe Badge
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Robinzor/tryhackme-badge-workflow@main