name: TryHackMe Update Badge

on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:

jobs:
  tryhackme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          pip install requests

      - name: Run TryHackMe Script
        env:
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_WORKSPACE: ${{ github.workspace }}
          username: 'Robinzor'
          commit_message: 'Add TryHackMe badge'
        run: python3 .github/workflows/tryhackme.py

      - name: Update README
        if: success()
        run: |
          awk '!/\[TryHackMe\]/ {print} /!\[TryHackMe\]/ {print "![TryHackMe Badge](Robinzor/.github/workflows/images/tryhackme.png)"}' README.md > README_temp.md && mv README_temp.md README.md
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add README.md
          git commit -m "Update TryHackMe badge in README"
          git push
