name: Update README with Badge

on:
  push:
    paths:
      - 'badge.png'

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update README
        run: |
          # Copy the latest badge.png to the root directory
          cp badge.png $GITHUB_WORKSPACE/badge.png

          # Update the README with the latest badge
          sed -i 's|!\[TryHackMe Badge\](badge.png)|\!\[TryHackMe Badge\](https://raw.githubusercontent.com/Robinzor/tryhackme-badge-workflow/main/badge.png)|g' $GITHUB_WORKSPACE/README.md

          # Commit and push the changes
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add badge.png README.md
          git commit -m "Update README with latest badge" || echo "No changes to commit"
          git push
